name: ChatMK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install PM2
        run: npm install -g pm2

      - name: Install backend dependencies
        run: npm ci

      - name: Build backend TypeScript
        run: npm run build

      - name: Generate Prisma Client
        run: npx prisma generate --schema=./backend/prisma/schema.prisma

      - name: Install frontend dependencies and build
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Deploy with PM2
        run: |
          pm2 stop all || true
          pm2 delete all || true
          pm2 start backend/dist/src/index.js --name chatmk --watch
